import AlertPanel from '../components/AlertPanel';
import { useSimulation } from '../context/SimulationContext';

export default function Alerts() {
  const { alerts, events } = useSimulation();

  return (
    <div className="p-6 max-w-[1600px] mx-auto">
      <h2 className="text-xl font-semibold text-slate-100 mb-1">Alerts</h2>
      <p className="text-sm text-slate-500 mb-6">Live operational alerts generated by the prediction engine.</p>

      <div className="grid grid-cols-1 xl:grid-cols-[1fr_340px] gap-6">
        <AlertPanel alerts={alerts} />

        <div>
          <div className="text-[11px] uppercase tracking-wide text-slate-500 mb-3">Event Log</div>
          <div className="panel divide-y divide-white/[0.05]">
            {events.length === 0 && <div className="px-4 py-6 text-center text-sm text-slate-500">No events yet.</div>}
            {events.map((e) => (
              <div key={e.id} className="px-4 py-3 text-sm">
                <div className="flex items-center justify-between">
                  <span className="font-medium text-slate-200">{e.label}</span>
                  <span className="text-xs text-slate-500 font-mono tabular">{e.timestamp}</span>
                </div>
                <div className="text-xs text-slate-500 mt-0.5">
                  {e.trainNumber} · {e.sectionFrom} → {e.sectionTo} · {e.impactMin > 0 ? `+${e.impactMin}` : e.impactMin} min
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
